version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/Maliev.Aspire.AppHost"
      - "/Maliev.Aspire.DatabaseSeeder"
      - "/Maliev.Aspire.ServiceDefaults"
      - "/Maliev.Aspire.ServiceDefaults.Tests"
      - "/Maliev.Aspire.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
