version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directories:
      - "/"
      - "/Maliev.Aspire.AppHost"
      - "/Maliev.Aspire.DatabaseSeeder"
      - "/Maliev.Aspire.ServiceDefaults"
      - "/Maliev.Aspire.ServiceDefaults.Tests"
      - "/Maliev.Aspire.Tests"
    schedule:
      interval: "weekly"
